//POST

export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE"

//get

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

//Delete


export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"

//order

export const ORDER_PRODUCT_REQUEST="ORDER_PRODUCT_REQUEST"
export const ORDER_PRODUCT_SUCCESS="ORDER_PRODUCT_SUCCESS"
export const ORDER_PRODUCT_FAILURE="ORDER_PRODUCT_FAILURE"

//Edit
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

//Login
export const LOGIN_PRODUCT_REQUEST="LOGIN_PRODUCT_REQUEST"
export const LOGIN_PRODUCT_SUCCESS="LOGIN_PRODUCT_SUCCESS"
export const LOGIN_PRODUCT_FAILURE="LOGIN_PRODUCT_FAILURE"